### ISSUE TITLE
Is there going to be a support for Symfony 6?

### ISSUE THREAD

**Issue by BackNot** [endroid/qr-code-bundle#60]
Hello, thanks for the bundle.

I was wondering if there is going to be a support for Symfony 6?

Thanks.

**Comment by endroid** [comment]
Hi @BackNot version 4.0.7 supports Symfony 6. If you have any issues please let me know.

**Comment by BackNot** [comment]
Hi @endroid. Thanks for the quick reaction. I still get the following deprecation message

`Method "Twig\Extension\ExtensionInterface::getFunctions()" might add "array" as a native return type declaration in the future. Do the same in implementation "Endroid\QrCodeBundle\Twig\QrCodeExtension" now to avoid errors or add an explicit @return annotation to suppress this message.`

I am using the 4.0.7 version. Is the problem with me?

Edit: I think the package is not updated in packagist

**Comment by endroid** [comment]
Hi @BackNot I checked for you and if you look at https://packagist.org/packages/endroid/qr-code-bundle you see version 4.0.7 so the version was correctly registered in Packagist. And the deprecation is fixed in https://github.com/endroid/qr-code-bundle/commit/a41c94a33d3381e09ef5376d95ad87998319ab55 which will be included in a future release. Please note that a deprecation message is just a notice that something will change in the future, not a bug ;)

**Comment by alexgit2k** [comment]
For the record, the deprecation notice also happens with Symfony 5.4.

Looking forward for the next release to have clean error-logs again.
