### ISSUE TITLE
question about recipes v installer

### ISSUE THREAD

**Issue by tacman** [endroid/qr-code-bundle#75]
Out of curiosity, why do you use the installer rather than a Symfony recipe?  I _think_ everything can be done in the recipe, since the installer is mostly to copy the package and route config.

Again, this is mostly just my own interest, I've been trying to publish recipes for my bundles, it's a bit of a pain. I had also tried rolling my own installation, but that had its own issues.  

Recipes are my least favorite part of the symfony ecosystem -- it seems much more intuitive that the recipe would be included in the bundle repo rather than a curated repo that requires a PR.  So are you happy with the installer as a solution?

Thanks, and thanks for releasing this bundle as well, it works great!

**Comment by endroid** [comment]
Hi @tacman good question. As you already said my installer just detects the framework and copies some files, nothing more. That's all I need and that's why I created it and keep it as simple as possible. Also there is an option to disable it when needed.

The reason I don't use recipes is that I like to keep my configuration with my source code / version, instead of a separate recipes server (once when the server was down, no configuration was installed) and 2.0 / 2.1 / 3.0 version folder structure. Also I don't like that I have to wait for recipes to be approved and merged before I can release a new version. That bothered me a lot when I was working with recipes: I should be able to make a change immediately and without any obstacles.

I wrote a post about this: https://medium.com/@endroid/auto-package-configuration-for-symfony-e14780e29d81

So it is not a statement against Flex in any way, just a way for me to be more efficient and have more control. Flex recipes have way more features and also have their advantages so it's free for anyone to choose ;)
